{% set name = "poetry-core" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/poetry_core-{{ version }}.tar.gz
  sha256: c1a1f6f00e4254742f40988a8caf665549101cf9991122cd5de1198897768b1a
  patches:
    - vcs.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<4.0.0

test:
  imports:
    - poetry.core
    - poetry.core._vendor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/poetry-core/
  summary: Poetry PEP 517 Build Backend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-poetry/poetry-core
  doc_url: https://github.com/python-poetry/poetry-core/blob/main/README.md

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
