{% set version = "1.1.0a6" %}

package:
  name: poetry-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry-core/poetry-core-{{ version }}.tar.gz
  sha256: e22c8897216216f6344b3d57167a8cd5485a1403934817d7efaf7fb8f6bcffc9
  patches:
    - vcs.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - intreehooks
  run:
    - python >=3.6
    # upstream claims this isn't needed for py>=38 but want to keep this noarchs
    # if possible
    - importlib_metadata >=1.7.0
    - dataclasses >=0.8

test:
  imports:
    - poetry.core
    - poetry.core._vendor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/poetry-core/
  summary: Core utilities for Poetry
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
