{% set version = "1.0.8" %}

package:
  name: poetry-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry-core/poetry-core-{{ version }}.tar.gz
  sha256: 951fc7c1f8d710a94cb49019ee3742125039fc659675912ea614ac2aa405b118
  patches:
    - vcs.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - intreehooks
  run:
    - python
    - importlib-metadata >=1.7.0,<2.0.0  # [py<38]

test:
  imports:
    - poetry.core
    - poetry.core._vendor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/poetry-core/
  summary: Core utilities for Poetry
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
